pipeline {
    agent {
        docker {
            image 'python:2.7.16-slim'
        }
    }

    stages{
        stage("build"){
            when{
                changeset "**/vote/**"
            }
            steps{
                echo 'Compiling vote app'
                dir('vote'){
                    sh 'pip install -r requirements.txt'
                }
            }
        }
        stage("test"){
            when{
                changeset "**/vote/**"
            }
            steps{
                echo 'Running Unit Tests on the vote app'
                dir('vote'){
                    sh 'nosetests -v'
                }

            }
        }
    }

    post{
        always{
            echo 'Building multibranch pipeline for worker is completed..'
        }
        failure{
            echo 'Pipeline failed. Would normally send Slack notification here.'
        }
        success{
            echo 'Pipeline succeeded. Would you really send a notification when there is success??'
        }
    }
}