pipeline {
    agent any

    tools {
        maven 'Maven 3.6.1'
    }

    stages{
        stage("build"){
            steps{
                echo 'Compiling worker app'
                dir('worker'){
                    sh 'mvn compile'
                }
            }
        }
        stage("test"){
            steps{
                echo 'Running Unit Tests on the worker app'
                dir('worker'){
                    sh 'mvn clean test'
                }

            }
        }
        stage("package"){
            steps{
                echo 'Packaging worker app'
                dir('worker'){
                    sh 'mvn package'
                }
            }
        }
        stage("docker-package"){
            when{
                branch 'master'
                changeset "**/worker/**"
            }
            steps{
                echo 'Packaging worker app with Docker'
                script{
                    docker.withRegistry('https://index.docker.io/v1', 'dockerlogin') {
                        def workerImage = docker.build("tplive/worker:v${env.BUILD_ID}", "./worker")
                        workerImage.push()
                        workerImage.push("${env.BRANCH_NAME}")
                    }
                }
            }
        }
    }

    post{
        always{
            echo 'Building multibranch pipeline for worker is completed..'
        }
    }
}